[env:freenove_wrover]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200

; The ESP32 Arduino core already bundles LittleFS, we just need to tell
; the builder that this is the filesystem we want to use
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson@^7.0.0
